schema_version = "1.0.0"
id = "rhubarb_lipsync"
version = "1.6.2"
name = "Rhubarb Lipsync NG"
tagline = "Integrate Rhubarb Lipsync into Blender"
maintainer = "Premysl Srubar"
type = "add-on"

website = "https://blendermarket.com/products/rhubarb-lipsync-ng"
tags = ["Animation"]

blender_version_min = "4.2.0"
license = ["SPDX:MIT"]

platforms = ["linux-x64"]
files = "Import/export sound files and captures, execute rhubarb cli file"